[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "upgrade-insecure-requests"

[[redirects]]
  from   = "/oauth2/*"
  to     = "https://starlist.store/:splat"
  status = 200
  force  = true 

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  