spring:
  application:
    name: starlist

  profiles:
    include:
      - db
      - oauth

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect